CREATE TABLE [dbo].[AspNetUsers] (
    [Id] [nvarchar](128) NOT NULL,
    [UserName]      NVARCHAR (MAX) NOT NULL,
    [PasswordHash]  NVARCHAR (MAX) NULL,
    [SecurityStamp] NVARCHAR (MAX) NULL,
    [EmailConfirmed]       BIT             NULL,
    [PhoneNumber]          NVARCHAR (MAX) NULL,
    [PhoneNumberConfirmed] BIT             NULL,
    [TwoFactorEnabled]     BIT             NULL,
    [LockoutEndDateUtc]    DATETIME       NULL,
    [LockoutEnabled]       BIT             NULL,
    [AccessFailedCount]    INT             NULL,
    [ApplicationId]                          UNIQUEIDENTIFIER default newid(),
    [LegacyPasswordHash]  NVARCHAR (MAX) NULL,
    [LoweredUserName]  NVARCHAR (256)    NULL,
    [MobileAlias]      NVARCHAR (16)    DEFAULT (NULL) NULL,
    [IsAnonymous]      BIT              DEFAULT ((0))  NULL,
    [LastActivityDate] DATETIME2          NULL,
    [MobilePIN]                              NVARCHAR (16)    NULL,
    [Email]                                  NVARCHAR (256)   NULL,
    [LoweredEmail]                           NVARCHAR (256)   NULL,
    [PasswordQuestion]                       NVARCHAR (256)   NULL,
	[NormalizedUserName]                           NVARCHAR (256)   NULL,
	[ConcurrencyStamp]                           NVARCHAR (256)   NULL,
	[LockoutEnd]                          DATETIME2  NULL,
	[NormalizedEmail]                           NVARCHAR (256)   NULL,
    [PasswordAnswer]                         NVARCHAR (128)   NULL,
    [IsApproved]                             BIT               NULL,
    [IsLockedOut]                            BIT               NULL,
    [CreateDate]                             DATETIME2                NULL,
    [LastLoginDate]                          DATETIME2          NULL,
    [LastPasswordChangedDate]                DATETIME2          NULL,
    [LastLockoutDate]                        DATETIME2          NULL,
    [FailedPasswordAttemptCount]             INT               NULL,
    [FailedPasswordAttemptWindowStart]       DATETIME2          NULL,
    [FailedPasswordAnswerAttemptCount]       INT               NULL,
    [FailedPasswordAnswerAttemptWindowStart] DATETIME2          NULL,
    [Comment]                                NTEXT            NULL,
    CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC)
);